[package]
name = "atlas-cli"
version = "0.0.1"
edition = "2024"


[dependencies]
config = "0.15.19"
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.8"

[dev-dependencies]
pretty_assertions = "1.4.1"
